export const institutes = [
  { id: 1, name: "Akkelpur Govt. Technical School and College" },
  { id: 2, name: "Amtali Govt. Technical School and College" },
  { id: 3, name: "Bagerhat Govt. Technical School and College" },
  { id: 4, name: "Baliakandi Govt. Technical School and College" },
  { id: 5, name: "Bancharampur Govt. Technical School and College" },
  { id: 6, name: "Bandarban Govt. Technical School and College" },
  { id: 7, name: "Bangladesh Education Board" },
  { id: 8, name: "Bangladesh Technical Education Board" },
  { id: 9, name: "Baniachong Govt. Technical School and College" },
  { id: 10, name: "Barguna Govt. Technical School and College" },
  { id: 11, name: "Barisal Govt. Technical School and College" },
  { id: 12, name: "Barura Govt.Technical School and College" },
  { id: 13, name: "Batiaghata Govt.Technical School and College" },
  { id: 14, name: "Begumganj Govt. Technical School And College" },
  { id: 15, name: "Belabo Govt. Technical School and College." },
  { id: 16, name: "Bhairab Govt. Technical School and College" },
  { id: 17, name: "Bhedarganj Govt. Technical School and College" },
  { id: 18, name: "Bheramara Govt. Technical School and College" },
  { id: 19, name: "Bhola Govt. Technical School and College" },
  { id: 20, name: "Bochaganj Govt. Technical School and College" },
  { id: 21, name: "Brahmanbaria Govt. Technical School and College" },
  { id: 22, name: "Central Store Cum Service Center" },
  { id: 23, name: "Chandpur Govt. Technical School and College" },
  { id: 24, name: "Chapai Nawabganj Govt. Technical School and College" },
  { id: 25, name: "Charghat Govt. Technical School and  College" },
  { id: 26, name: "Chatak Govt. Technical School and College" },
  { id: 27, name: "Chatkhil Govt. Technical school and college" },
  { id: 28, name: "Chauddagram Govt. Technical School and College" },
  { id: 29, name: "Chuadanga Govt. Technical School and College" },
  { id: 30, name: "College Of Textile Technology (Ex)" },
  { id: 31, name: "Coxsbazar Govt. Technical School and College" },
  { id: 32, name: "Damudya Govt. Technical School and college" },
  { id: 33, name: "Debiganj Govt. Technical School and College, Panchagarh" },
  { id: 34, name: "Dewangonj Govt. Technical School  College" },
  { id: 35, name: "Dhamrai Govt. Technical School and College" },
  { id: 36, name: "Dhubaura Govt. Technical School and College" },
  { id: 37, name: "Dighinala Govt. Technical School And College" },
  { id: 38, name: "Dimla Govt. Technical School and College" },
  { id: 39, name: "Dinajpur Govt. Technical School and College" },
  { id: 40, name: "Directorate Of Technical Education" },
  { id: 41, name: "Dowarabazar Govt. Technical School and College" },
  { id: 42, name: "Dumuria Govt. Technical School and College" },
  { id: 43, name: "Dupchachia Govt. Technical School and College" },
  { id: 44, name: "Durgapur Govt. Technical School and College" },
  { id: 45, name: "Fatikchari Govt. Technical School and College" },
  { id: 46, name: "Feni Govt. Technical School and College" },
  { id: 47, name: "Gaibandha Govt. Technical School and College" },
  { id: 48, name: "Galachipa Govt.Technical School and College" },
  { id: 49, name: "Gazaria Govt. Technical School and College" },
  { id: 50, name: "Gazipur Govt. Technical School and College" },
  { id: 51, name: "Goalanda Govt. Technical School and College" },
  { id: 52, name: "Golapganj Govt. Technical School and College" },
  { id: 53, name: "Gopalganj Govt. Technical School and College" },
  { id: 54, name: "Gopalpur Govt. Technical School And College" },
  { id: 55, name: "Gouripur Govt. Technical School and College" },
  { id: 56, name: "Graphic Arts Institute" },
  { id: 57, name: "Gurudaspur Govt. Technical School and College" },
  { id: 58, name: "Habiganj Govt. Technical School and College" },
  { id: 59, name: "Hajiganj Govt. Technical School and Collage" },
  { id: 60, name: "Haripur Govt.Technical School and Collage" },
  { id: 61, name: "Harirampur Govt. Technical School and College" },
  { id: 62, name: "Hizla Govt. Technical School And College" },
  { id: 63, name: "Hosenabad Govt. Technical School and College" },
  { id: 64, name: "Itna Govt. Technical School and College" },
  { id: 65, name: "Jamalpur Govt. Technical School and College" },
  { id: 66, name: "Jessore Govt. Technical School and College" },
  { id: 67, name: "Jhalakathi Govt. Technical School and College" },
  { id: 68, name: "Jhenaidah Govt. Technical School and College" },
  { id: 69, name: "Jibonnagar Govt. Technical School and College" },
  { id: 70, name: "Joypara Govt. Technical School and College" },
  { id: 71, name: "Joypurhat Govt. Technical School and College" },
  { id: 72, name: "Juri Govt. Technical School and College" },
  { id: 73, name: "Kachua Govt. Technical School and College" },
  { id: 74, name: "Kalia Govt. Technical School and College" },
  { id: 75, name: "Kaliganj Govt. Technical School and College, lalmonirhat." },
  { id: 76, name: "Kaliganj Govt. Technical School and College, satkhira" },
  { id: 77, name: "Kapasia Govt. Technical school and College" },
  { id: 78, name: "Kasba Govt. Technical School and College" },
  { id: 79, name: "Kasba Technical School and College" },
  { id: 80, name: "Kashiani Govt. Technical School  College" },
  { id: 81, name: "Kawkhali Govt. Technical School and College" },
  { id: 82, name: "Keshabpur Govt. Technical School and College" },
  { id: 83, name: "Khagrachori Govt. Technical School and College" },
  { id: 84, name: "Kishoreganj Govt. Technical School and College" },
  { id: 85, name: "Kuliarchar Govt. Technical School and College" },
  { id: 86, name: "Kurigram Govt. Technical School and College" },
  { id: 87, name: "Kustia Govt. Technical School and College" },
  { id: 88, name: "kutubdia Govt. Technical School and College" },
  { id: 89, name: "Lakshmipur Govt. Technical School and College" },
  { id: 90, name: "Lalmohan Govt. Technical School and College" },
  { id: 91, name: "Lalmonirhat Govt. Technical School and College" },
  { id: 92, name: "Madarganj Govt. Technical School and College" },
  { id: 93, name: "Madaripur Govt. Technical School and College" },
  { id: 94, name: "Madhabpur Govt. Technical School and College" },
  { id: 95, name: "Magura Govt. Technical School and College" },
  { id: 96, name: "Maijdee Govt. Technical School and College" },
  { id: 97, name: "Manikgonj Govt. Technical School and College" },
  { id: 98, name: "Manirampur Govt. Technical School and College" },
  { id: 99, name: "Meherpur Govt. Technical School and College" },
  { id: 100, name: "Ministry Of Education," },
  { id: 101, name: "Mithamain Govt. Technical School and College" },
  { id: 102, name: "Mohammadpur Govt. Technical School and College" },
  { id: 103, name: "Mongla Govt. Technical School and College" },
  { id: 104, name: "Moulovibazar Govt. Technical School and College" },
  { id: 105, name: "Mujibnagar Govt. Technical School and College" },
  { id: 106, name: "Munshiganj Govt. Technical School and College" },
  { id: 107, name: "Muradnagar Govt. Technical School and College" },
  { id: 108, name: "Nachole Govt. Technical School and College" },
  { id: 109, name: "Nagarpur Govt. Technical School and College" },
  { id: 110, name: "Nageshwari Govt. Technical School and College" },
  { id: 111, name: "Naikhongchhari  Govt. Technical School and College" },
  { id: 112, name: "Nalitabari Govt. Technical School and College" },
  { id: 113, name: "Nandail  Govt. Technical and College" },
  { id: 114, name: "Naogaon  Govt. Technical School and College" },
  { id: 115, name: "Narail Govt. Technical School and College" },
  { id: 116, name: "Narayanganj  Govt. Technical School and Collage" },
  { id: 117, name: "Narshingdi  Govt. Technical School and College" },
  { id: 118, name: "Natore Govt. Technical School and College" },
  { id: 119, name: "Nawabgonj Govt. Technical School and College" },
  { id: 120, name: "Nazirpur Govt. Technical School and College" },
  { id: 121, name: "Nctb" },
  { id: 122, name: "Netrokona  Govt. Technical School and College" },
  { id: 123, name: "Nilphamari Govt. Technical School and College" },
  { id: 124, name: "Nsdc" },
  { id: 125, name: "Pabna  Govt. Technical School and College" },
  { id: 126, name: "Paikgachha Govt. Technical School  and College" },
  { id: 127, name: "Panchagarh  Govt. Technical School and College" },
  { id: 128, name: "Parbotipur  Govt. Technical School and College" },
  { id: 129, name: "Patnitala Govt. Technical School and College" },
  { id: 130, name: "Patuakhali  Govt. Technical School and College" },
  { id: 131, name: "Pirganj Govt. Technical School and College, Rangpur" },
  { id: 132, name: "Pirganj Govt. Technical School and College, Thakurgaon" },
  { id: 133, name: "Pirojpur  Govt. Technical School and College" },
  { id: 134, name: "Rajbari  Govt. Technical School and College" },
  { id: 135, name: "Rajnagar Govt. Technical School and College" },
  { id: 136, name: "Ramgati Govt. Technical School and College" },
  { id: 137, name: "Rampal Govt. Technical School and College." },
  { id: 138, name: "Rangpur Govt. Technical School and College" },
  { id: 139, name: "Raozan Govt. Technical School and College" },
  { id: 140, name: "Regional Director Office, Barishal" },
  { id: 141, name: "Regional Director Office, Dhaka" },
  { id: 142, name: "Regional Director Office, Khulna" },
  { id: 143, name: "Regional Inspector Office Rajshahi" },
  { id: 144, name: "Regional Inspector Office, Comilla" },
  { id: 145, name: "Saghata Government Technical School and College" },
  { id: 146, name: "Saidpur Govt. Technical School and College" },
  { id: 147, name: "Saltha Govt. Technical School and College" },
  { id: 148, name: "Santhia Govt. Technical School and College" },
  { id: 149, name: "Sapahar Govt. Technical School and college" },
  { id: 150, name: "Satkhira Govt. Technical School and College" },
  { id: 151, name: "Shahjadpur Govt. Technical School and College" },
  { id: 152, name: "Shailkupa Govt. Technical School and College" },
  { id: 153, name: "Shalikha Govt. Technical School and College" },
  { id: 154, name: "Shariatpur Govt. Technical School and College" },
  { id: 155, name: "Sharsha Govt. Technical School and College" },
  { id: 156, name: "Sherpur Govt. Technical School and College" },
  { id: 157, name: "Shibalaya Govt. Technical School  College" },
  { id: 158, name: "Shibchar Govt. Technical School and College" },
  { id: 159, name: "Shyamanagar Govt. Technical School and College,Satkhira" },
  { id: 160, name: "Singra Govt. Technical School and College" },
  { id: 161, name: "Sirajganj Govt. Technical School and College" },
  { id: 162, name: "Sitakunda Govt. Technical School and College" },
  { id: 163, name: "Skills And Training Enhancement Project" },
  { id: 164, name: "Skills Development Project" },
  { id: 165, name: "Sunamganj Govt. Technical School and College" },
  { id: 166, name: "Sylhet Govt. Technical School and College" },
  { id: 167, name: "Tangail Govt. Technical School and College" },
  { id: 168, name: "Tanore Govt. Technical school and Collage" },
  { id: 169, name: "Technical Teachers Training College" },
  { id: 170, name: "Teknaf Govt. Technical School and College" },
  { id: 171, name: "Tetulia Govt. Technical School and College" },
  { id: 172, name: "Thakurgaon Govt. Technical School and College" },
  { id: 173, name: "Tungipara Govt. Technical School and College" },
  { id: 174, name: "Vocational Teachers Training Institute" },
];